# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\guest\ConfirmedBooking\BookingConfirmed.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1000, 600)
        Dialog.setStyleSheet("background-color: rgb(93, 93, 93);")
        self.sidepanel_L = QtWidgets.QLabel(Dialog)
        self.sidepanel_L.setGeometry(QtCore.QRect(10, 10, 241, 581))
        self.sidepanel_L.setText("")
        self.sidepanel_L.setObjectName("sidepanel_L")
        self.sidepanel_R = QtWidgets.QLabel(Dialog)
        self.sidepanel_R.setGeometry(QtCore.QRect(750, 10, 241, 581))
        self.sidepanel_R.setText("")
        self.sidepanel_R.setObjectName("sidepanel_R")
        self.Title = QtWidgets.QLabel(Dialog)
        self.Title.setGeometry(QtCore.QRect(270, 20, 461, 71))
        font = QtGui.QFont()
        font.setFamily("Open Sans Extrabold")
        font.setPointSize(26)
        self.Title.setFont(font)
        self.Title.setStyleSheet("color: rgb(238, 238, 238);")
        self.Title.setFrameShape(QtWidgets.QFrame.Box)
        self.Title.setAlignment(QtCore.Qt.AlignCenter)
        self.Title.setObjectName("Title")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(270, 160, 461, 281))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(3)
        self.frame.setObjectName("frame")
        self.LabelBookingID = QtWidgets.QLabel(self.frame)
        self.LabelBookingID.setGeometry(QtCore.QRect(40, 40, 381, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LabelBookingID.setFont(font)
        self.LabelBookingID.setStyleSheet("color: rgb(238, 238, 238);")
        self.LabelBookingID.setObjectName("LabelBookingID")
        self.LabelUserID = QtWidgets.QLabel(self.frame)
        self.LabelUserID.setGeometry(QtCore.QRect(40, 120, 381, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LabelUserID.setFont(font)
        self.LabelUserID.setStyleSheet("color: rgb(238, 238, 238);")
        self.LabelUserID.setObjectName("LabelUserID")
        self.LabelPeformanceID = QtWidgets.QLabel(self.frame)
        self.LabelPeformanceID.setGeometry(QtCore.QRect(40, 200, 381, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LabelPeformanceID.setFont(font)
        self.LabelPeformanceID.setStyleSheet("color: rgb(238, 238, 238);")
        self.LabelPeformanceID.setObjectName("LabelPeformanceID")
        self.BackToMenuButton = QtWidgets.QPushButton(Dialog)
        self.BackToMenuButton.setGeometry(QtCore.QRect(360, 490, 291, 51))
        font = QtGui.QFont()
        font.setFamily("Open Sans Extrabold")
        font.setPointSize(18)
        self.BackToMenuButton.setFont(font)
        self.BackToMenuButton.setStyleSheet("color: rgb(238, 238, 238);")
        self.BackToMenuButton.setObjectName("BackToMenuButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Title.setText(_translate("Dialog", "Booking Confirmed"))
        self.LabelBookingID.setText(_translate("Dialog", "Booking Reference No:"))
        self.LabelUserID.setText(_translate("Dialog", "UserID:"))
        self.LabelPeformanceID.setText(_translate("Dialog", "PeformanceID:"))
        self.BackToMenuButton.setText(_translate("Dialog", "Return To Menu"))
